spring.application.name=intelli-wallet
spring.profiles.default=dev
spring.datasource.url=jdbc:postgresql://${INTELLI_DB_HOST:localhost}:${INTELLI_DB_PORT:5432}/${INTELLI_DB_NAME:intelliwallet}
spring.datasource.username=${INTELLI_DB_USER:intelliwallet}
spring.datasource.password=${INTELLI_DB_PASSWORD:intelliwallet_dev}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.open-in-view=false
spring.docker.compose.enabled=false
